post http://localhost:3000/api/product/add
Content-Type: application/json

{
  "name": "Royal - White/Mesh/40",
"type" : "Watch",
"collection" : 1,
"sex" : "M",
"price" : 3100000,
"stock" : 15,
"sold" : 95,
"view" : 188,
"link" : "royal-white-mesh-40",
"description" : "Dyoss Royal White - chiếc đồng hồ khoác lên mình bộ áo kiêu kì rosegold - phụ kiện tuy đơn giản nhưng vô cùng sang trọng khi kết hợp cùng bộ suits lịch lãm hoặc thậm chí là trang phục casual hàng ngày.",
"features" : [
  "Đường kính 40mm - dành cho Nam.",
                "Máy Quartz Miyota Nhật Bản.",
                "Mặt kính Sapphire chống trầy cao cấp.",
                "Chống nước 5ATM (có thể đeo khi bơi - không khuyến khích).",
                "Vỏ đồng hồ và khoá bằng thép không gỉ.",
                "Dây thép nhập khẩu, không gỉ, sơn tĩnh diện - size 20mm.",
                "Bảo hành 1 năm cho máy và thay pin miễn phí."
],
"images" : [
                "https://www.dyoss.com/app/uploads/2018/08/upweb_gocchinh12_rosegold-9.jpg",
                "https://www.dyoss.com/app/uploads/2018/08/upweb_gocnghieng12_rosegold-8.jpg",
                "https://www.dyoss.com/app/uploads/2018/08/upweb_gocsau12_rosegold-9.jpg"
            ]
}